export const holdemCup = {
    currency: 'BYN',
    name: "Brunson Hold'em Cup",
    breakAfter: 6,
    breakDuration: 10,
    schedule:[
        {
            name: '1 Уровень',
            duration: 15,
            smallBlind: 25,
            bigBlind: 50,
        },
        {
            name: '2 Уровень',
            duration: 15,
            smallBlind: 50,
            bigBlind: 100,
        },
        {
            name: '3 Уровень',
            duration: 15,
            smallBlind: 75,
            bigBlind: 150,
        },
        {
            name: '4 Уровень',
            duration: 15,
            smallBlind: 100,
            bigBlind: 200,
        },
        {
            name: '5 Уровень',
            duration: 15,
            smallBlind: 125,
            bigBlind: 250,
        },
        {
            name: '6 Уровень',
            duration: 15,
            smallBlind: 150,
            bigBlind: 300,
        },
        {
            name: '7 Уровень',
            duration: 12,
            smallBlind: 200,
            bigBlind: 400,
        },
        {
            name: '8 Уровень',
            duration: 12,
            smallBlind: 300,
            bigBlind: 600,
        },
        {
            name: '9 Уровень',
            duration: 12,
            smallBlind: 400,
            bigBlind: 800,
        },
        {
            name: '10 Уровень',
            duration: 12,
            smallBlind: 500,
            bigBlind: 1000
        },
        {
            name: '11 Уровень',
            duration: 12,
            smallBlind: 750,
            bigBlind: 1500,
        },
        {
            name: '12 Уровень',
            duration: 12,
            smallBlind: 1000,
            bigBlind: 2000,
        },
        {
            name: '13 Уровень',
            duration: 12,
            smallBlind: 1500,
            bigBlind: 3000,
        },
        {
            name: '14 Уровень',
            duration: 12,
            smallBlind: 2000,
            bigBlind: 4000,
        },
        {
            name: '15 Уровень',
            duration: 12,
            smallBlind: 2500,
            bigBlind: 5000,
        },
        {
            name: '16 Уровень',
            duration: 12,
            smallBlind: 3000,
            bigBlind: 6000,
        },
        {
            name: '17 Уровень',
            duration: 12,
            smallBlind: 3500,
            bigBlind: 7000,
        },
        {
            name: '18 Уровень',
            duration: 12,
            smallBlind: 4000,
            bigBlind: 8000,
        },
        {
            name: '19 Уровень',
            duration: 12,
            smallBlind: 5000,
            bigBlind: 10000,
        },
        {
            name: '--',
            duration: 10,
            smallBlind: 0,
            bigBlind: 0,
        },
    ]
};
export const knockout = {
    currency: 'BYN',
    name: "Brunson KNOCKOUT",
    breakAfter: 6,
    breakDuration: 10,
    schedule:[
        {
            name: '1 Уровень',
            duration: 15,
            smallBlind: 25,
            bigBlind: 50,
        },
        {
            name: '2 Уровень',
            duration: 15,
            smallBlind: 50,
            bigBlind: 100,
        },
        {
            name: '3 Уровень',
            duration: 15,
            smallBlind: 75,
            bigBlind: 150,
        },
        {
            name: '4 Уровень',
            duration: 15,
            smallBlind: 100,
            bigBlind: 200,
        },
        {
            name: '5 Уровень',
            duration: 15,
            smallBlind: 125,
            bigBlind: 250,
        },
        {
            name: '6 Уровень',
            duration: 15,
            smallBlind: 150,
            bigBlind: 300,
        },
        {
            name: '7 Уровень',
            duration: 15,
            smallBlind: 200,
            bigBlind: 400,
        },
        {
            name: '8 Уровень',
            duration: 15,
            smallBlind: 300,
            bigBlind: 600,
        },
        {
            name: '9 Уровень',
            duration: 10,
            smallBlind: 400,
            bigBlind: 800,
        },
        {
            name: '10 Уровень',
            duration: 15,
            smallBlind: 500,
            bigBlind: 1000
        },
        {
            name: '11 Уровень',
            duration: 15,
            smallBlind: 750,
            bigBlind: 1500,
        },
        {
            name: '12 Уровень',
            duration: 15,
            smallBlind: 1000,
            bigBlind: 2000,
        },
        {
            name: '13 Уровень',
            duration: 15,
            smallBlind: 1500,
            bigBlind: 3000,
        },
        {
            name: '14 Уровень',
            duration: 15,
            smallBlind: 2000,
            bigBlind: 4000,
        },
        {
            name: '15 Уровень',
            duration: 15,
            smallBlind: 2500,
            bigBlind: 5000,
        },
        {
            name: '16 Уровень',
            duration: 15,
            smallBlind: 3000,
            bigBlind: 6000,
        },
        {
            name: '17 Уровень',
            duration: 15,
            smallBlind: 3500,
            bigBlind: 7000,
        },
        {
            name: '18 Уровень',
            duration: 15,
            smallBlind: 4000,
            bigBlind: 8000,
        },
        {
            name: '19 Уровень',
            duration: 15,
            smallBlind: 5000,
            bigBlind: 10000,
        },
        {
            name: '--',
            duration: 15,
            smallBlind: 0,
            bigBlind: 0,
        },
    ]
};
export const knockoutVIP = {
    currency: 'BYN',
    name: "Brunson VIP KNOCKOUT",
    breakAfter: 6,
    breakDuration: 15,
    schedule:[
        {
            name: '1 Уровень',
            duration: 15,
            smallBlind: 25,
            bigBlind: 50,
        },
        {
            name: '2 Уровень',
            duration: 15,
            smallBlind: 50,
            bigBlind: 100,
        },
        {
            name: '3 Уровень',
            duration: 15,
            smallBlind: 75,
            bigBlind: 150,
        },
        {
            name: '4 Уровень',
            duration: 15,
            smallBlind: 100,
            bigBlind: 200,
        },
        {
            name: '5 Уровень',
            duration: 15,
            smallBlind: 125,
            bigBlind: 250,
        },
        {
            name: '6 Уровень',
            duration: 15,
            smallBlind: 150,
            bigBlind: 300,
        },
        {
            name: '7 Уровень',
            duration: 15,
            smallBlind: 200,
            bigBlind: 400,
        },
        {
            name: '8 Уровень',
            duration: 15,
            smallBlind: 300,
            bigBlind: 600,
        },
        {
            name: '9 Уровень',
            duration: 10,
            smallBlind: 400,
            bigBlind: 800,
        },
        {
            name: '10 Уровень',
            duration: 15,
            smallBlind: 500,
            bigBlind: 1000
        },
        {
            name: '11 Уровень',
            duration: 15,
            smallBlind: 750,
            bigBlind: 1500,
        },
        {
            name: '12 Уровень',
            duration: 15,
            smallBlind: 1000,
            bigBlind: 2000,
        },
        {
            name: '13 Уровень',
            duration: 15,
            smallBlind: 1500,
            bigBlind: 3000,
        },
        {
            name: '14 Уровень',
            duration: 15,
            smallBlind: 2000,
            bigBlind: 4000,
        },
        {
            name: '15 Уровень',
            duration: 15,
            smallBlind: 2500,
            bigBlind: 5000,
        },
        {
            name: '16 Уровень',
            duration: 15,
            smallBlind: 3000,
            bigBlind: 6000,
        },
        {
            name: '17 Уровень',
            duration: 15,
            smallBlind: 3500,
            bigBlind: 7000,
        },
        {
            name: '18 Уровень',
            duration: 15,
            smallBlind: 4000,
            bigBlind: 8000,
        },
        {
            name: '19 Уровень',
            duration: 15,
            smallBlind: 5000,
            bigBlind: 10000,
        },
        {
            name: '--',
            duration: 15,
            smallBlind: 0,
            bigBlind: 0,
        },
    ]
};
export const youngGuns = {
    currency: 'BYN',
    name: "Brunson Young GUNS",
    prize: '50x4 BYN',
    breakAfter: 6,
    breakDuration: 15,
    schedule:[
        {
            name: '1 Уровень',
            duration: 12,
            smallBlind: 25,
            bigBlind: 50,
        },
        {
            name: '2 Уровень',
            duration: 12,
            smallBlind: 50,
            bigBlind: 100,
        },
        {
            name: '3 Уровень',
            duration: 12,
            smallBlind: 75,
            bigBlind: 150,
        },
        {
            name: '4 Уровень',
            duration: 12,
            smallBlind: 100,
            bigBlind: 200,
        },
        {
            name: '5 Уровень',
            duration: 12,
            smallBlind: 125,
            bigBlind: 250,
        },
        {
            name: '6 Уровень',
            duration: 12,
            smallBlind: 150,
            bigBlind: 300,
        },
        {
            name: '7 Уровень',
            duration: 10,
            smallBlind: 200,
            bigBlind: 400,
        },
        {
            name: '8 Уровень',
            duration: 10,
            smallBlind: 300,
            bigBlind: 600,
        },
        {
            name: '9 Уровень',
            duration: 10,
            smallBlind: 400,
            bigBlind: 800,
        },
        {
            name: '10 Уровень',
            duration: 10,
            smallBlind: 500,
            bigBlind: 1000
        },
        {
            name: '11 Уровень',
            duration: 10,
            smallBlind: 750,
            bigBlind: 1500,
        },
        {
            name: '12 Уровень',
            duration: 10,
            smallBlind: 1000,
            bigBlind: 2000,
        },
        {
            name: '13 Уровень',
            duration: 10,
            smallBlind: 1500,
            bigBlind: 3000,
        },
        {
            name: '14 Уровень',
            duration: 10,
            smallBlind: 2000,
            bigBlind: 4000,
        },
        {
            name: '15 Уровень',
            duration: 10,
            smallBlind: 2500,
            bigBlind: 5000,
        },
        {
            name: '16 Уровень',
            duration: 10,
            smallBlind: 3000,
            bigBlind: 6000,
        },
        {
            name: '17 Уровень',
            duration: 10,
            smallBlind: 3500,
            bigBlind: 7000,
        },
        {
            name: '18 Уровень',
            duration: 10,
            smallBlind: 4000,
            bigBlind: 8000,
        },
        {
            name: '19 Уровень',
            duration: 10,
            smallBlind: 5000,
            bigBlind: 10000,
        },
        {
            name: '--',
            duration: 10,
            smallBlind: 0,
            bigBlind: 0,
        },
    ]
};

export const championsCup = {
    currency: 'BYN',
    name: "Brunson CHAMPIONS Cup",
    breakAfter: 6,
    breakDuration: 15,
    schedule:[
        {
            name: '1 Уровень',
            duration: 20,
            smallBlind: 25,
            bigBlind: 50,
        },
        {
            name: '2 Уровень',
            duration: 20,
            smallBlind: 50,
            bigBlind: 100,
        },
        {
            name: '3 Уровень',
            duration: 20,
            smallBlind: 75,
            bigBlind: 150,
        },
        {
            name: '4 Уровень',
            duration: 20,
            smallBlind: 100,
            bigBlind: 200,
        },
        {
            name: '5 Уровень',
            duration: 20,
            smallBlind: 125,
            bigBlind: 250,
        },
        {
            name: '6 Уровень',
            duration: 20,
            smallBlind: 150,
            bigBlind: 300,
        },
        {
            name: '7 Уровень',
            duration: 20,
            smallBlind: 200,
            bigBlind: 400,
        },
        {
            name: '8 Уровень',
            duration: 20,
            smallBlind: 300,
            bigBlind: 600,
        },
        {
            name: '9 Уровень',
            duration: 20,
            smallBlind: 400,
            bigBlind: 800,
        },
        {
            name: '10 Уровень',
            duration: 20,
            smallBlind: 500,
            bigBlind: 1000
        },
        {
            name: '11 Уровень',
            duration: 20,
            smallBlind: 750,
            bigBlind: 1500,
        },
        {
            name: '12 Уровень',
            duration: 20,
            smallBlind: 1000,
            bigBlind: 2000,
        },
        {
            name: '13 Уровень',
            duration: 20,
            smallBlind: 1500,
            bigBlind: 3000,
        },
        {
            name: '14 Уровень',
            duration: 20,
            smallBlind: 2000,
            bigBlind: 4000,
        },
        {
            name: '15 Уровень',
            duration: 20,
            smallBlind: 2500,
            bigBlind: 5000,
        },
        {
            name: '16 Уровень',
            duration: 20,
            smallBlind: 3000,
            bigBlind: 6000,
        },
        {
            name: '17 Уровень',
            duration: 20,
            smallBlind: 3500,
            bigBlind: 7000,
        },
        {
            name: '18 Уровень',
            duration: 20,
            smallBlind: 4000,
            bigBlind: 8000,
        },
        {
            name: '19 Уровень',
            duration: 20,
            smallBlind: 5000,
            bigBlind: 10000,
        },
        {
            name: '--',
            duration: 10,
            smallBlind: 0,
            bigBlind: 0,
        },
    ]
};